### ISSUE TITLE
Hospedagem

### ISSUE THREAD

**Issue by insidegui** [naofode/naofo.de#11]
Quero ajudar, por favor entre em contato (meu e-mail está disponível no meu perfil do github).

**Comment by edbizarro** [comment]
+1, posso ajudar a hospedar

**Comment by elieserleao** [comment]
+1 na hospedagem também. ;)

**Comment by naofode** [comment]
O que precisarem de informação, é só escrever pra pedromoraes arroba gmail. Quando montarem os clones, mando o dump do banco e coloco redirecionamento no naofo.de para os clones

**Comment by naofode** [comment]
Pra constar: um camarada postou algumas instruções sobre deploy com apache no readme. Abs!
